name: "Execução manual"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalação de dependências
        run: |
          npm install -g yarn
          yarn install
          yarn add cypress cypress-mochawesome-reporter @faker-js/faker mocha@latest

      - name: Executando testes
        run: yarn run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-report-${{ github.run_number }}
          path: cypress/reports/html/
