name: 'Execução manual'

on:
    workflow_dispatch:


jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Instalando yarn
              run: npm install -g yarn

            - name: Instalando dependências
              run: yarn

            - name: Instalando playwright
              run: yarn add cypress

            - name: Executando testes
              run: yarn run e2e

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: cypress-report-${{ github.run_number }}
                  path: cypress/reports/html/